from setuptools import find_packages, setup

setup(
    name='standard_repo',
    version='0.1.0',
    packages=find_packages(),
    python_requires='>=3.8',
    install_requires=[
        'torch>=2.0.0',
        'torchvision>=0.15.0',
        'numpy>=1.21.0',
        'matplotlib>=3.5.0',
        'pandas>=1.3.0',
        'scipy>=1.7.0',
        'scikit-learn>=1.0.0',
        'tqdm>=4.60.0',
        'pyyaml>=6.0',
        'pillow>=8.3.0',
        'einops>=0.6.0',
        'termcolor>=1.1.0',
        'h5py>=3.0.0',
    ],
    author='Tao Zhang',
    author_email='zhangtao@westlake.edu.cn',
    description='A standard research project template for deep learning and scientific computing',
    long_description=open('README.md', encoding='utf-8').read(),
    long_description_content_type='text/markdown',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
    ],
)
